# https://github.com/pages-themes/minimal/tree/master#usage
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Benjamin Bolgakov
logo: /assets/img/logo.png
google_analytics:
